### ISSUE TITLE
Issue with Nuget Package

### ISSUE THREAD

**Issue by TaylorTheDeveloper** [jlattimer/D365AppInsights#2]
Hey Jlattimer,

First, I just wanted to say thanks for taking the time to make and share this wrapper. I believe the nuget package is not configured correctly as when I try to install the reference from Nuget it is added to the project but I'm unable to resolve any references for things like AiLogger, etc..

However I'm able to build the project and add the dll manually things seem to work, so I think there is just an issue in the nuget configuration. 

Thanks and take care,
T

**Comment by jlattimer** [comment]
But there is no DLL, the NuGet package only includes the C# source files to make everything work. This way there is no need to worry about ILMerging an assembly if deploying Online. 

The only thing you'd need to do extra before creating the logger is to add a project reference to System.Net.Http.

**Comment by TaylorTheDeveloper** [comment]
Ahh I understand. In that case then I don't think anything is being pulled down as I'm unable to resolve the namespace.

**Comment by jlattimer** [comment]
So do you get anything at all or any errors in the output of Visual Studio? Can you create a sample project after you've added and post it?
